#!/bin/sh
# dckrm - Remove Docker Containers
# $ dckrm

set -eu

[ -v DCKRM_TEMPDIR ] || DCKRM_TEMPDIR="/tmp"
[ -v DCKRM_EDITOR ] || DCKRM_EDITOR="vi"

TEMPFILE=$DCKRM_TEMPDIR/dckrm-$(date +%Y%m%d%H%M%S)

_remove() {
    docker rm $(grep -v "^ *#" $1 | grep -v "^ *$" | cut -f 1)
    rm $1
}

if [ -e $TEMPFILE ]
then
    echo "ERROR! temporary file $TEMPFILE already exists!"
    exit 1
else
    echo "# dckrm - Remove Docker Containers" > $TEMPFILE
    echo "# NAMES    IMAGE    COMMAND    CREATED    STATUS    PORTS" >> $TEMPFILE
    docker ps -a --format "{{.Names}}\t{{.Image}}\t{{.Command}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}" >> $TEMPFILE
    $DCKRM_EDITOR $TEMPFILE
    while true
    do
        printf "Do you remove docker containers? [Y/n] > "
        read answer

        case $answer in
            [Yy])
                _remove $TEMPFILE
                break
                ;;
            "")
                _remove $TEMPFILE
                break
                ;;
            n)
                rm $TEMPFILE
                break
                ;;

            *)
                ;;
        esac
    done
fi
