#!/bin/sh
# dckrmi - Remove Docker Images
# $ dckrmi

set -eu

[ -v DCKRM_TEMPDIR ] || DCKRM_TEMPDIR="/tmp"
[ -v DCKRM_EDITOR ] || DCKRM_EDITOR="vi"

TEMPFILE=$DCKRM_TEMPDIR/dckrmi-$(date +%Y%m%d%H%M%S)

_remove() {
    docker rmi $(grep -v "^ *#" $1 | grep -v "^ *$" | cut -f 1)
    rm $1
}


if [ -e $TEMPFILE ]
then
    echo "ERROR! temporary file $TEMPFILE already exists!"
    exit 1
else
    echo "# dckrm - Remove Docker Images" > $TEMPFILE
    echo "# IMAGE ID    REPOSITORY    TAG    CREATED SINCE    SIZE" >> $TEMPFILE
    docker images --format "{{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.CreatedSince}}\t{{.Size}}" >> $TEMPFILE
    $DCKRM_EDITOR $TEMPFILE
    while true
    do
        printf "Do you remove docker images? [Y/n] > "
        read answer

        case $answer in
            [Yy])
                _remove $TEMPFILE
                break
                ;;
            "")
                _remove $TEMPFILE
                break
                ;;
            n)
                rm $TEMPFILE
                break
                ;;

            *)
                ;;
        esac
    done
fi
